import React, { useState } from "react";
import { FaExclamationTriangle } from "react-icons/fa";
import { FiSend, FiPaperclip, FiMic } from "react-icons/fi";
import { MdQuickreply } from "react-icons/md";
import { useAuth } from "../../Context/authContext";
import { useNavigate } from "react-router";

const JoinUsingAI = () => {
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [isError, setIsError] = useState(false);
  const [isQuestion, setIsQuestion] = useState(false);
  const [OKReply, setOKReply] = useState("Hello! How can i assist you today?");
  const {userName, userId} = useAuth();
  const navigate = useNavigate();

  const sendToAI = async (e) => {
    e.preventDefault();

    if (input.length < 3) return;

    setSending(true);
    
    const response = await fetch(
      "https://ai-based-quiz-builder-quizfy-backend.onrender.com/AIFeatures/sendMessageForAIPoweredQuiz",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ message: input }),
      }
    );
    
    const data = await response.json();
    let cleaned = data.reply;
    setInput("");
    
    // remove markdown code fences
    if (typeof cleaned === "string" && cleaned.includes("```")) {
      cleaned = cleaned.replace(/```json|```/g, "").trim();
    }

    let parsed;
    try {
      parsed = JSON.parse(cleaned);
    } catch (err) {
      console.error("JSON parse failed:", err);
      parsed = { status: "ERROR", reply: "⚠️Something went wrong!" };
    }

    if (parsed?.status == "ERROR" || parsed?.status == "OK") {//A simple reply from AI
      setIsError(true);
      setOKReply(parsed.reply);
    } 
    else if (parsed.length > 0 || parsed?.status === "QUESTION") {//A question set generated by AI
      console.log("user question");
      setIsQuestion(true);

      const res = await fetch("https://ai-based-quiz-builder-quizfy-backend.onrender.com/AIFeatures/AddQuestionGeneratedByAI", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ questions: parsed, userId , userName }),
      });
      const data = await res.json();
      console.log(data);

      if(response.ok){
        setIsQuestion(false);
        navigate(`/Quiz/AIQuiz/${data.presentationId}`);
      }
      else{
        setIsQuestion(false);
        setIsError(true);
        setOKReply("⚠️Something went wrong while creating quiz. Please try again.");
      }
    }

    setSending(false);

    console.log(parsed);
  };

  if (sending)
    return (
      <div className="fixed inset-0 w-screen h-screen bg-white flex flex-col justify-center items-center z-50 gap-4">
        <div className="relative">
          <div className="h-14 w-14 rounded-full border-4 border-indigo-200"></div>
          <div className="h-14 w-14 rounded-full border-4 border-indigo-500 border-t-transparent animate-spin absolute top-0 left-0"></div>
        </div>

        <p className="text-gray-600 font-Outfit animate-pulse text-sm">
          Sending your prompt… Please wait.
        </p>
      </div>
    );

  if (isError)
    return (
      <div className="fixed inset-0 w-screen h-screen bg-stone-950/80 flex items-center justify-center z-50 animate-fadeIn">
        <div className="bg-white rounded-2xl shadow-xl p-8 w-[90%] max-w-md flex flex-col items-center text-center gap-6">
          <MdQuickreply className="text-green-500 text-6xl animate-bounce" />

          <h1 className="text-2xl font-semibold text-stone-800">
            Reply From Quizify
          </h1>

          <p className="text-stone-600 text-sm leading-relaxed">{OKReply}</p>

          <button
            onClick={() => setIsError(false)}
            className="px-6 py-2 bg-indigo-500 hover:bg-indigo-600 text-white rounded-lg transition-all duration-200"
          >
            Understood
          </button>
        </div>
      </div>
    );

  if (isQuestion)
    return (
<div className="fixed inset-0 w-screen h-screen bg-white flex flex-col justify-center items-center z-50 gap-4">
        <div className="relative">
          <div className="h-14 w-14 rounded-full border-4 border-indigo-200"></div>
          <div className="h-14 w-14 rounded-full border-4 border-indigo-500 border-t-transparent animate-spin absolute top-0 left-0"></div>
        </div>

        <p className="text-gray-600 font-Outfit animate-pulse text-sm">
          Building up your Quiz. Wait for some time....
        </p>
      </div>
    );

  return (
    <main className="flex flex-col items-center justify-center h-screen bg-white font-[Outfit] text-gray-800 px-4">
      {/* Logo / Title Section */}
      <div className="flex flex-col items-center text-center mb-10">
        <h1 className="text-4xl font-semibold bg-gradient-to-r from-indigo-500 to-indigo-700 bg-clip-text text-transparent mb-2">
          Quizify AI
        </h1>
        <p className="text-gray-500 text-sm">
          Give a prompt and let AI create a quiz and join as a user and answer
          them all!
        </p>
      </div>

      {/* Center Input Box */}
      <form className="w-full max-w-2xl flex items-center bg-gray-50 border border-gray-200 rounded-3xl px-4 py-3 shadow-md focus-within:ring-2 focus-within:ring-indigo-300 transition">
        {/* Attach Icon */}

        {/* Input Field */}
        <input
          type="text"
          placeholder="Generate 10 hard level SSC Questions"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="flex-1 bg-transparent outline-none px-3 text-gray-700 placeholder-gray-400"
        />

        {/* Send Icon */}
        <button
          onClick={sendToAI}
          type="submit"
          className="text-indigo-500 hover:text-indigo-600 ml-3 transition"
        >
          <FiSend className="text-xl" />
        </button>
      </form>

      {/* Small footer-style info  */}
      <div className="text-xs text-gray-400 mt-6 text-center">
        Quizify AI can only generate quiz type questions based on your prompts
        and you can directly answer them.
        <br/>
        The AI Generated quiz that you will join and solve will be available in My Presentation Section.
      </div>
    </main>
  );
};

export default JoinUsingAI;
